application: YOUR_APP_ID
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /(.*\.(css|js))
  static_files: static/\1
  upload: static/(.*\.(css|js))

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest