application: allmyplus
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "7d"

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /info\.html
  static_files: static/info.html
  upload: static/info\.html

- url: .*
  script: main.app

